# Generated by Django 4.2.18 on 2026-08-25 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anonymous_messages', '0002_alter_qaquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_ref', models.CharField(db_index=True, max_length=120, unique=True)),
                ('flw_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('flw_transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('transaction_type', models.CharField(choices=[('gift', 'Direct Creator Gift'), ('paid_qa_access', 'Paid Q&A Session Pass'), ('super_question', 'Super Question Boost'), ('super_message', 'Super Message Tip'), ('payout', 'Creator Withdrawal Payout')], default='gift', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('donor_alias', models.CharField(blank=True, default='Generous Anon', max_length=100, null=True)),
                ('gift_note', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_transactions', to='anonymous_messages.anonymousmessage')),
                ('qa_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_transactions', to='anonymous_messages.qasession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('account_number', models.CharField(blank=True, default='', max_length=30)),
                ('account_name', models.CharField(blank=True, default='', max_length=100)),
                ('minimum_gift_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('allow_gifting', models.BooleanField(default=True)),
                ('show_leaderboard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('processing', 'Processing Flutterwave Transfer'), ('completed', 'Completed / Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flw_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('sender_alias', models.CharField(default='Generous Anon', max_length=100)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(choices=[('Bronze Supporter', 'Bronze Supporter'), ('Silver VIP', 'Silver VIP'), ('Gold Champion', 'Gold Champion'), ('Diamond Legend', 'Diamond Legend'), ('Angel Backer', 'Angel Backer')], default='Bronze Supporter', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_detail', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QASessionAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='Pass Holder', max_length=100)),
                ('access_token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_accesses', to='anonymous_messages.qasession')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_records', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_session_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'email')},
            },
        ),
    ]
