# Generated by Django 5.2.15 on 2026-06-29 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('image', 'Image'), ('gif', 'GIF')], default='text', max_length=10)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_duration', models.IntegerField(blank=True, null=True)),
                ('media_thumbnail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reaction', models.CharField(blank=True, max_length=10, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sender_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='anonymous_messages.anonymousmessage')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questioner_session', models.CharField(blank=True, max_length=100, null=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='anonymous_messages.qaquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QASession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('max_questions', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='qaquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='anonymous_messages.qasession'),
        ),
        migrations.CreateModel(
            name='QAUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_session', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_set', to='anonymous_messages.qaquestion')),
            ],
            options={
                'unique_together': {('question', 'voter_session')},
            },
        ),
    ]
