# Generated by Django 4.2.7 on 2026-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmessage',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
