# Generated by Django 4.2.18 on 2026-08-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qaquestion',
            options={'ordering': ['-is_pinned', '-is_super_question', '-upvotes', 'created_at']},
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='creator_reply',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='gift_currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='is_public_on_wall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='is_super_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='super_message_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='qaanswer',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaquestion',
            name='asker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qaquestion',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='qaquestion',
            name='gift_currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='qaquestion',
            name='is_super_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qasession',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='qasession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qasession',
            name='paid_perks',
            field=models.TextField(blank=True, default='Access to private live Q&A stream, priority question submission, and exclusive creator answers.'),
        ),
        migrations.AddField(
            model_name='qasession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='qasession',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
